import os
import subprocess
import re

def get_git_info():
    try:
        count = subprocess.check_output(['git', 'rev-list', '--count', 'HEAD'], stderr=subprocess.STDOUT).strip().decode('utf-8')
        hash_str = subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD'], stderr=subprocess.STDOUT).strip().decode('utf-8')
        status = subprocess.check_output(['git', 'status', '--porcelain'], stderr=subprocess.STDOUT).strip().decode('utf-8')
        return f"{count}", f"{hash_str}{'-dirty' if status else ''}"
    except Exception:
        return "0", "unknown"

def generate():
    try:
        Import("env") # SCons / PlatformIO hook
        root_dir = env.get("PROJECT_DIR")
    except NameError:
        root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    version_file = os.path.join(root_dir, 'version.txt')
    header_file = os.path.join(root_dir, 'lib', 'microreader', 'version.h')
    
    base_version = "2.0-dev"
    if os.path.exists(version_file):
        with open(version_file, 'r', encoding='utf-8') as f:
            base_version = f.read().strip()
            
    build_count, git_hash = get_git_info()
    full_version = f"{base_version}.{build_count}"
    
    header_content = f"""// Auto-generated by tools/generate_version.py
#pragma once

#define MICROREADER_VERSION "{full_version}"
#define MICROREADER_GIT_HASH "{git_hash}"
"""
    
    # Write only if changed to avoid unnecessary recompilations
    current_content = ""
    if os.path.exists(header_file):
        with open(header_file, 'r', encoding='utf-8') as f:
            current_content = f.read()

    if current_content != header_content:
        with open(header_file, 'w', encoding='utf-8') as f:
            f.write(header_content)
        print(f"Generated version.h: {full_version}")

generate()
