#include <gtest/gtest.h>

#include <vector>

#include "FontLoader.h"
#include "microreader/content/BitmapFont.h"

// ---------------------------------------------------------------------------
// Synthetic unit tests — no real font files required.
// These run in both unit_tests and microreader_tests.
// ---------------------------------------------------------------------------

TEST(BitmapFontSyntheticTest, NullDataIsInvalid) {
  microreader::BitmapFont font(nullptr, 0);
  EXPECT_FALSE(font.valid());
}

TEST(BitmapFontSyntheticTest, ZeroSizeDataIsInvalid) {
  uint8_t dummy = 0;
  microreader::BitmapFont font(&dummy, 0);
  EXPECT_FALSE(font.valid());
}

TEST(BitmapFontSyntheticTest, WrongMagicIsInvalid) {
  // The MBF magic is "MBF1" (or similar). Garbage bytes must not be valid.
  std::vector<uint8_t> junk(64, 0xAB);
  microreader::BitmapFont font(junk.data(), junk.size());
  EXPECT_FALSE(font.valid());
}

TEST(BitmapFontSyntheticTest, TruncatedHeaderIsInvalid) {
  // 4-byte header prefix only — far too short to be valid.
  uint8_t buf[4] = {'M', 'B', 'F', '1'};
  microreader::BitmapFont font(buf, 4);
  EXPECT_FALSE(font.valid());
}

// ---------------------------------------------------------------------------
// Real font file tests — load the actual .mbf files generated by generate_font.py.
// These are excluded from unit_tests (SMOKE_TESTS_ONLY) and only run in
// microreader_tests, since they depend on the resources/fonts/ directory.
// ---------------------------------------------------------------------------
#ifndef SMOKE_TESTS_ONLY

static constexpr struct {
  microreader::FontSize size;
  const char* suffix;
} kRealSizes[] = {
    {microreader::FontSize::Small,   "small"  },
    {microreader::FontSize::Normal,  "normal" },
    {microreader::FontSize::Large,   "large"  },
    {microreader::FontSize::XLarge,  "xlarge" },
    {microreader::FontSize::XXLarge, "xxlarge"},
};

// Each generated .mbf file must be valid and have sensible header metrics.
TEST(BitmapFontRealFileTest, AllSizesLoadAndAreValid) {
  for (const auto& s : kRealSizes) {
    auto data = load_mbf(s.suffix);
    ASSERT_FALSE(data.empty()) << "Missing font-" << s.suffix << ".mbf — run generate_font.py first";
    microreader::BitmapFont font(data.data(), data.size());
    EXPECT_TRUE(font.valid()) << s.suffix;
    EXPECT_GT(font.num_glyphs(), 0u) << s.suffix;
    EXPECT_GT(font.y_advance(), 0) << s.suffix;
    EXPECT_GT(font.baseline(), 0) << s.suffix;
    EXPECT_GT(font.glyph_height(), 0) << s.suffix;
  }
}

// Larger pixel-size files should have greater or equal y_advance than smaller ones.
TEST(BitmapFontRealFileTest, MetricsScaleWithSize) {
  std::vector<std::vector<uint8_t>> data(microreader::kFontSizeCount);
  std::vector<microreader::BitmapFont> fonts(microreader::kFontSizeCount);
  for (size_t i = 0; i < microreader::kFontSizeCount; ++i) {
    data[i] = load_mbf(kRealSizes[i].suffix);
    ASSERT_FALSE(data[i].empty()) << kRealSizes[i].suffix;
    fonts[i].init(data[i].data(), data[i].size());
    ASSERT_TRUE(fonts[i].valid()) << kRealSizes[i].suffix;
  }
  // Small ≤ Normal ≤ Large ≤ XLarge ≤ XXLarge
  for (size_t i = 1; i < microreader::kFontSizeCount; ++i) {
    EXPECT_LE(fonts[i - 1].y_advance(), fonts[i].y_advance())
        << kRealSizes[i - 1].suffix << " should not be taller than " << kRealSizes[i].suffix;
  }
}

// Common printable ASCII characters must be present with non-zero advance widths.
TEST(BitmapFontRealFileTest, CommonAsciiGlyphsPresent) {
  auto data = load_mbf("normal");
  ASSERT_FALSE(data.empty());
  microreader::BitmapFont font(data.data(), data.size());
  ASSERT_TRUE(font.valid());

  for (char c : {'A', 'Z', 'a', 'z', '0', '9', '?', '.', ',', ' '}) {
    EXPECT_GT(font.char_width(c, microreader::FontStyle::Regular), 0) << "zero advance for '" << c << "'";
  }
}

// Bold, italic, and bold-italic styles must be present (generated with --with-styles).
TEST(BitmapFontRealFileTest, AllStyleVariantsPresent) {
  auto data = load_mbf("normal");
  ASSERT_FALSE(data.empty());
  microreader::BitmapFont font(data.data(), data.size());
  ASSERT_TRUE(font.valid());

  EXPECT_TRUE(font.has_style(microreader::FontStyle::Regular));
  EXPECT_TRUE(font.has_style(microreader::FontStyle::Bold)) << "Bold style missing — was --with-styles used?";
  EXPECT_TRUE(font.has_style(microreader::FontStyle::Italic)) << "Italic style missing";
  EXPECT_TRUE(font.has_style(microreader::FontStyle::BoldItalic)) << "BoldItalic style missing";
}

// Bold glyphs should have non-zero advance widths for common letters.
// (Bold is not guaranteed to be wider than Regular for all typefaces.)
TEST(BitmapFontRealFileTest, BoldGlyphsHaveNonZeroWidth) {
  auto data = load_mbf("normal");
  ASSERT_FALSE(data.empty());
  microreader::BitmapFont font(data.data(), data.size());
  ASSERT_TRUE(font.valid());
  if (!font.has_style(microreader::FontStyle::Bold))
    GTEST_SKIP() << "Bold style not present";

  for (char c : {'A', 'B', 'H', 'M', 'W', 'a', 'b', 'e'}) {
    EXPECT_GT(font.char_width(c, microreader::FontStyle::Bold), 0) << "Bold '" << c << "' has zero advance";
  }
}

// Grayscale planes must be present (generated with --with-styles which includes gray data).
TEST(BitmapFontRealFileTest, GrayscalePlanesPresent) {
  auto data = load_mbf("normal");
  ASSERT_FALSE(data.empty());
  microreader::BitmapFont font(data.data(), data.size());
  ASSERT_TRUE(font.valid());
  EXPECT_TRUE(font.has_grayscale()) << "No grayscale planes — was the font generated with gray support?";
}

// BitmapFontSet loaded with all 5 sizes must be valid and dispatch correctly.
TEST(BitmapFontRealFileTest, BitmapFontSetLoadsAllSizes) {
  std::vector<std::vector<uint8_t>> data(microreader::kFontSizeCount);
  std::vector<microreader::BitmapFont> fonts(microreader::kFontSizeCount);
  microreader::BitmapFontSet font_set;

  for (size_t i = 0; i < microreader::kFontSizeCount; ++i) {
    data[i] = load_mbf(kRealSizes[i].suffix);
    ASSERT_FALSE(data[i].empty()) << kRealSizes[i].suffix;
    fonts[i].init(data[i].data(), data[i].size());
    ASSERT_TRUE(fonts[i].valid()) << kRealSizes[i].suffix;
    font_set.set(kRealSizes[i].size, &fonts[i]);
  }

  EXPECT_TRUE(font_set.valid());
  for (const auto& s : kRealSizes) {
    EXPECT_GT(font_set.char_width('A', microreader::FontStyle::Regular, s.size), 0) << s.suffix;
    EXPECT_GT(font_set.y_advance(s.size), 0) << s.suffix;
  }
}

#endif  // SMOKE_TESTS_ONLY
