#include <gtest/gtest.h>

#include <chrono>
#include <filesystem>
#include <string>
#include <vector>

#include "FontLoader.h"
#include "ScreenshotDisplay.h"
#include "microreader/display/DrawBuffer.h"
#include "microreader/screens/ReaderScreen.h"

using Clock = std::chrono::steady_clock;
using Ms = std::chrono::duration<double, std::milli>;
static double elapsed_ms(Clock::time_point a, Clock::time_point b) {
  return std::chrono::duration_cast<Ms>(b - a).count();
}

using namespace microreader;
namespace fs = std::filesystem;

static std::string sanitize_filename(const std::string& name) {
  std::string out;
  out.reserve(name.size());
  for (char c : name) {
    if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-' || c == '_' ||
        c == '.') {
      out += c;
    } else if (c == ' ') {
      out += '_';
    }
  }
  return out.empty() ? "book" : out;
}

struct PageInfo {
  std::string filename;
  size_t chapter;
  size_t page_in_chapter;
};

static bool write_html_index(const fs::path& html_path, const std::string& title, const std::vector<PageInfo>& pages) {
  std::ofstream out(html_path);
  if (!out.good())
    return false;

  out << "<!DOCTYPE html>\n";
  out << "<html lang=\"en\">\n";
  out << "<head>\n";
  out << "  <meta charset=\"UTF-8\">\n";
  out << "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
  out << "  <title>" << title << "</title>\n";
  out << "  <style>\n";
  out << "    body{margin:0;padding:16px;font-family:Arial,sans-serif;background:#f7f7f7;color:#111;}\n";
  out << "    h1{margin:0 0 16px;font-size:1.8rem;}\n";
  out << "    section{margin-bottom:32px;}\n";
  out << "    section h2{margin:0 0 12px;font-size:1.2rem;color:#222;}\n";
  out << "    "
         ".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(480px,480px));gap:16px;justify-items:start;"
         "justify-content:center;}"
         "\n";
  out << "    figure{margin:0;width:480px;display:flex;flex-direction:column;align-items:center;}\n";
  out << "    .image-frame{width:480px;height:788px;border-radius:12px;border:1px solid "
         "#e3e3e3;background:#fff;box-shadow:0 8px 24px "
         "rgba(0,0,0,0.06);display:flex;align-items:center;justify-content:center;}\n";
  out << "    img{width:480px;height:788px;object-fit:contain;border-radius:12px 12px 12px 12px;}\n";
  out << "    figcaption{margin-top:4px;color:#333;font-size:0.95rem;text-align:center;}\n";
  out << "    footer{margin-top:24px;font-size:0.95rem;color:#666;}\n";
  out << "  </style>\n";
  out << "</head>\n";
  out << "<body>\n";
  out << "  <h1>" << title << "</h1>\n";

  if (!pages.empty()) {
    size_t current_chapter = pages[0].chapter;
    out << "  <section>\n";
    out << "    <h2>Chapter " << (current_chapter + 1) << "</h2>\n";
    out << "    <div class=\"grid\">\n";

    for (const auto& page : pages) {
      if (page.chapter != current_chapter) {
        out << "    </div>\n";
        out << "  </section>\n";
        current_chapter = page.chapter;
        out << "  <section>\n";
        out << "    <h2>Chapter " << (current_chapter + 1) << "</h2>\n";
        out << "    <div class=\"grid\">\n";
      }
      out << "      <figure>\n";
      out << "        <div class=\"image-frame\">\n";
      out << "          <img src=\"" << page.filename << "\" alt=\"Page " << page.page_in_chapter << "\">\n";
      out << "        </div>\n";
      out << "        <figcaption>Page " << page.page_in_chapter << "</figcaption>\n";
      out << "      </figure>\n";
    }

    out << "    </div>\n";
    out << "  </section>\n";
  }

  out << "  <footer>Generated by microreader export test.</footer>\n";
  out << "</body>\n";
  out << "</html>\n";
  return true;
}

static std::vector<fs::path> discover_epubs(const fs::path& dir) {
  std::vector<fs::path> result;
  if (!fs::exists(dir) || !fs::is_directory(dir))
    return result;
  for (auto& entry : fs::directory_iterator(dir)) {
    if (!entry.is_regular_file())
      continue;
    if (entry.path().extension() == ".epub")
      result.push_back(entry.path());
  }
  std::sort(result.begin(), result.end());
  return result;
}

struct BookStats {
  bool ok = false;
  std::string name;
  size_t pages = 0;
  double open_ms = 0;
  double render_ms = 0;
  double save_ms = 0;
  double total_ms = 0;
};

static BookStats export_book_to_html(const fs::path& epub_path, const fs::path& output_root,
                                     const BitmapFontSet& font_set) {
  ScreenshotDisplay display;
  DrawBuffer buf(display);
  ReaderScreen screen;
  screen.set_path(epub_path.string());
  screen.set_fonts(&font_set);

  fs::path book_dir = output_root / sanitize_filename(epub_path.stem().string());
  fs::remove_all(book_dir);
  fs::create_directories(book_dir);
  fs::path data_dir = book_dir / "data";
  fs::create_directories(data_dir);
  screen.set_data_dir(data_dir.string());

  auto t0 = Clock::now();
  screen.start(buf);
  auto t1 = Clock::now();

  BookStats stats;
  stats.name = epub_path.stem().string();

  if (!screen.is_open_ok()) {
    std::cerr << "Failed to open book: " << epub_path << std::endl;
    return stats;
  }

  std::vector<PageInfo> pages;
  size_t current_chapter = screen.current_chapter_index();
  size_t page_in_chapter = 1;
  size_t page_number = 1;

  auto add_page = [&](const fs::path& filename) {
    pages.push_back(PageInfo{filename.filename().string(), current_chapter, page_in_chapter});
  };

  double total_render_ms = 0;
  double total_save_ms = 0;

  fs::path page_file = book_dir / "page_1.png";
  auto ts = Clock::now();
  ScreenshotDisplay::save_image(buf, page_file.string());
  total_save_ms += elapsed_ms(ts, Clock::now());
  add_page(page_file);

  while (true) {
    auto trA = Clock::now();
    bool ok = screen.next_page_and_render(buf);
    total_render_ms += elapsed_ms(trA, Clock::now());
    if (!ok)
      break;

    const size_t chapter = screen.current_chapter_index();
    if (chapter != current_chapter) {
      current_chapter = chapter;
      page_in_chapter = 1;
    } else {
      page_in_chapter++;
    }
    page_number++;
    page_file = book_dir / ("page_" + std::to_string(page_number) + ".png");
    ts = Clock::now();
    ScreenshotDisplay::save_image(buf, page_file.string());
    total_save_ms += elapsed_ms(ts, Clock::now());
    add_page(page_file);
  }

  auto t2 = Clock::now();

  bool ok = write_html_index(book_dir / "index.html", epub_path.stem().string(), pages);
  auto t3 = Clock::now();

  stats.ok = ok;
  stats.pages = pages.size();
  stats.open_ms = elapsed_ms(t0, t1);
  stats.render_ms = total_render_ms;
  stats.save_ms = total_save_ms;
  stats.total_ms = elapsed_ms(t0, t3);

  if (!ok)
    std::cerr << "Failed to write HTML index for: " << epub_path << std::endl;
  screen.stop();
  return stats;
}

static void print_stats(const BookStats& s) {
  printf("  %-40s  %4zu pages  render %5.0fms  save %5.0fms  total %5.0fms\n", s.name.c_str(), s.pages, s.render_ms,
         s.save_ms, s.total_ms);
}

static void print_summary(const std::vector<BookStats>& all) {
  size_t total_pages = 0;
  double total_render = 0, total_save = 0, total_total = 0;
  for (const auto& s : all) {
    total_pages += s.pages;
    total_render += s.render_ms;
    total_save += s.save_ms;
    total_total += s.total_ms;
  }
  printf("  %s\n", std::string(80, '-').c_str());
  printf("  %-40s  %4zu pages  render %5.0fms  save %5.0fms  total %5.0fms\n", "TOTAL", total_pages, total_render,
         total_save, total_total);
  if (!all.empty())
    printf("  avg %.1fms/page\n", total_total / (double)total_pages);
}

TEST(HtmlExportTest, ExportSmallFolderToHtml) {
  BitmapFontSet font_set;
  std::vector<BitmapFont> prop_fonts(kFontSizeCount);
  std::vector<std::vector<uint8_t>> font_data(kFontSizeCount);
  ASSERT_TRUE(load_desktop_fonts(font_set, prop_fonts, font_data));

  fs::path input_dir = fs::path(small_books_dir());
  ASSERT_TRUE(fs::exists(input_dir));

  fs::path output_root = fs::path(repo_root()) / "test" / "output" / "html_export_folder";
  std::error_code ec;
  fs::create_directories(output_root, ec);
  ASSERT_TRUE(fs::exists(output_root) || !ec) << "output_root=" << output_root << " ec=" << ec.message();

  auto books = discover_epubs(input_dir);
  ASSERT_FALSE(books.empty());

  printf("\nExporting %zu books:\n", books.size());
  std::vector<BookStats> all_stats;
  for (const auto& epub_path : books) {
    BookStats s = export_book_to_html(epub_path, output_root, font_set);
    ASSERT_TRUE(s.ok) << "Failed to export " << epub_path.filename().string();
    print_stats(s);
    all_stats.push_back(s);
  }
  print_summary(all_stats);
}

TEST(HtmlExportTest, ExportAliceIllustrated) {
  BitmapFontSet font_set;
  std::vector<BitmapFont> prop_fonts(kFontSizeCount);
  std::vector<std::vector<uint8_t>> font_data(kFontSizeCount);
  ASSERT_TRUE(load_desktop_fonts(font_set, prop_fonts, font_data));

  fs::path epub_path = fs::path(small_books_dir()) / "alice-illustrated.epub";
  ASSERT_TRUE(fs::exists(epub_path)) << "alice-illustrated.epub not found in test/books/small/";

  fs::path output_root = fs::path(repo_root()) / "test" / "output" / "alice_illustrated";
  std::error_code ec;
  fs::create_directories(output_root, ec);

  BookStats s = export_book_to_html(epub_path, output_root, font_set);
  ASSERT_TRUE(s.ok);
  print_stats(s);
  std::cout << "\nOutput: " << (output_root / "alice-illustrated" / "index.html") << std::endl;
}

TEST(HtmlExportTest, ExportRegressionTest) {
  BitmapFontSet font_set;
  std::vector<BitmapFont> prop_fonts(kFontSizeCount);
  std::vector<std::vector<uint8_t>> font_data(kFontSizeCount);
  ASSERT_TRUE(load_desktop_fonts(font_set, prop_fonts, font_data));

  fs::path epub_path = fs::path(books_dir()) / "regression_test.epub";
  ASSERT_TRUE(fs::exists(epub_path)) << "regression_test.epub not found in test/books/";

  fs::path output_root = fs::path(repo_root()) / "test" / "output" / "regression_test";
  std::error_code ec;
  fs::create_directories(output_root, ec);

  BookStats s = export_book_to_html(epub_path, output_root, font_set);
  ASSERT_TRUE(s.ok);
  print_stats(s);
  std::cout << "\nOutput: " << (output_root / "regression_test" / "index.html") << std::endl;
}
